# Generated by Django 2.1.7 on 2019-03-14 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20190314_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='received_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
