# Generated by Django 2.1.7 on 2019-03-14 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contact_received_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='received_date',
        ),
    ]
