# Generated by Django 2.1.7 on 2019-03-16 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20190316_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='categories.Subcategory'),
        ),
    ]
