# Generated by Django 2.1.7 on 2019-03-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20190313_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='<django.db.models.fields.CharField>'),
        ),
    ]
